extern crate bindgen;
extern crate cc;

use std::thread;
use std::env;
use std::path::PathBuf;

const ZXING_SRC: &'static str = "zxing/core/src";

const FILE_LIST: [&'static str; 221] = [
    "bigint/BigInteger.cc",
    "bigint/BigInteger.cc",
    "bigint/BigInteger.hh",
    "bigint/BigInteger.hh",
    "bigint/BigIntegerAlgorithms.cc",
    "bigint/BigIntegerAlgorithms.cc",
    "bigint/BigIntegerAlgorithms.hh",
    "bigint/BigIntegerAlgorithms.hh",
    "bigint/BigIntegerLibrary.hh",
    "bigint/BigIntegerLibrary.hh",
    "bigint/BigIntegerUtils.cc",
    "bigint/BigIntegerUtils.cc",
    "bigint/BigIntegerUtils.hh",
    "bigint/BigIntegerUtils.hh",
    "bigint/BigUnsigned.cc",
    "bigint/BigUnsigned.cc",
    "bigint/BigUnsigned.hh",
    "bigint/BigUnsigned.hh",
    "bigint/BigUnsignedInABase.cc",
    "bigint/BigUnsignedInABase.cc",
    "bigint/BigUnsignedInABase.hh",
    "bigint/BigUnsignedInABase.hh",
    "bigint/NumberlikeArray.hh",
    "bigint/NumberlikeArray.hh",
    "zxing/aztec/AztecDetectorResult.cpp",
    "zxing/aztec/AztecDetectorResult.h",
    "zxing/aztec/AztecReader.cpp",
    "zxing/aztec/AztecReader.h",
    "zxing/aztec/decoder/Decoder.cpp",
    "zxing/aztec/decoder/Decoder.h",
    "zxing/aztec/detector/Detector.cpp",
    "zxing/aztec/detector/Detector.h",
    "zxing/BarcodeFormat.cpp",
    "zxing/BarcodeFormat.h",
    "zxing/Binarizer.cpp",
    "zxing/Binarizer.h",
    "zxing/BinaryBitmap.cpp",
    "zxing/BinaryBitmap.h",
    "zxing/ChecksumException.cpp",
    "zxing/ChecksumException.h",
    "zxing/common/Array.h",
    "zxing/common/BitArray.cpp",
    "zxing/common/BitArray.h",
    "zxing/common/BitArrayIO.cpp",
    "zxing/common/BitMatrix.cpp",
    "zxing/common/BitMatrix.h",
    "zxing/common/BitSource.cpp",
    "zxing/common/BitSource.h",
    "zxing/common/CharacterSetECI.cpp",
    "zxing/common/CharacterSetECI.h",
    "zxing/common/Counted.h",
    "zxing/common/DecoderResult.cpp",
    "zxing/common/DecoderResult.h",
    "zxing/common/detector/JavaMath.h",
    "zxing/common/detector/MathUtils.h",
    "zxing/common/detector/MonochromeRectangleDetector.cpp",
    "zxing/common/detector/MonochromeRectangleDetector.h",
    "zxing/common/detector/WhiteRectangleDetector.cpp",
    "zxing/common/detector/WhiteRectangleDetector.h",
    "zxing/common/DetectorResult.cpp",
    "zxing/common/DetectorResult.h",
    "zxing/common/GlobalHistogramBinarizer.cpp",
    "zxing/common/GlobalHistogramBinarizer.h",
    "zxing/common/GreyscaleLuminanceSource.cpp",
    "zxing/common/GreyscaleLuminanceSource.h",
    "zxing/common/GreyscaleRotatedLuminanceSource.cpp",
    "zxing/common/GreyscaleRotatedLuminanceSource.h",
    "zxing/common/GridSampler.cpp",
    "zxing/common/GridSampler.h",
    "zxing/common/HybridBinarizer.cpp",
    "zxing/common/HybridBinarizer.h",
    "zxing/common/IllegalArgumentException.cpp",
    "zxing/common/IllegalArgumentException.h",
    "zxing/common/PerspectiveTransform.cpp",
    "zxing/common/PerspectiveTransform.h",
    "zxing/common/Point.h",
    "zxing/common/reedsolomon/GenericGF.cpp",
    "zxing/common/reedsolomon/GenericGF.h",
    "zxing/common/reedsolomon/GenericGFPoly.cpp",
    "zxing/common/reedsolomon/GenericGFPoly.h",
    "zxing/common/reedsolomon/ReedSolomonDecoder.cpp",
    "zxing/common/reedsolomon/ReedSolomonDecoder.h",
    "zxing/common/reedsolomon/ReedSolomonException.cpp",
    "zxing/common/reedsolomon/ReedSolomonException.h",
    "zxing/common/Str.cpp",
    "zxing/common/Str.h",
    "zxing/common/StringUtils.cpp",
    "zxing/common/StringUtils.h",
    "zxing/datamatrix/DataMatrixReader.cpp",
    "zxing/datamatrix/DataMatrixReader.h",
    "zxing/datamatrix/decoder/BitMatrixParser.cpp",
    "zxing/datamatrix/decoder/BitMatrixParser.h",
    "zxing/datamatrix/decoder/DataBlock.cpp",
    "zxing/datamatrix/decoder/DataBlock.h",
    "zxing/datamatrix/decoder/DecodedBitStreamParser.cpp",
    "zxing/datamatrix/decoder/DecodedBitStreamParser.h",
    "zxing/datamatrix/decoder/Decoder.cpp",
    "zxing/datamatrix/decoder/Decoder.h",
    "zxing/datamatrix/detector/CornerPoint.cpp",
    "zxing/datamatrix/detector/CornerPoint.h",
    "zxing/datamatrix/detector/Detector.cpp",
    "zxing/datamatrix/detector/Detector.h",
    "zxing/datamatrix/detector/DetectorException.cpp",
    "zxing/datamatrix/detector/DetectorException.h",
    "zxing/datamatrix/Version.cpp",
    "zxing/datamatrix/Version.h",
    "zxing/DecodeHints.cpp",
    "zxing/DecodeHints.h",
    "zxing/Exception.cpp",
    "zxing/Exception.h",
    "zxing/FormatException.cpp",
    "zxing/FormatException.h",
    "zxing/IllegalStateException.h",
    "zxing/InvertedLuminanceSource.cpp",
    "zxing/InvertedLuminanceSource.h",
    "zxing/LuminanceSource.cpp",
    "zxing/LuminanceSource.h",
    "zxing/multi/ByQuadrantReader.cpp",
    "zxing/multi/ByQuadrantReader.h",
    "zxing/multi/GenericMultipleBarcodeReader.cpp",
    "zxing/multi/GenericMultipleBarcodeReader.h",
    "zxing/multi/MultipleBarcodeReader.cpp",
    "zxing/multi/MultipleBarcodeReader.h",
    "zxing/multi/qrcode/detector/MultiDetector.cpp",
    "zxing/multi/qrcode/detector/MultiDetector.h",
    "zxing/multi/qrcode/detector/MultiFinderPatternFinder.cpp",
    "zxing/multi/qrcode/detector/MultiFinderPatternFinder.h",
    "zxing/multi/qrcode/QRCodeMultiReader.cpp",
    "zxing/multi/qrcode/QRCodeMultiReader.h",
    "zxing/MultiFormatReader.cpp",
    "zxing/MultiFormatReader.h",
    "zxing/NotFoundException.h",
    "zxing/oned/CodaBarReader.cpp",
    "zxing/oned/CodaBarReader.h",
    "zxing/oned/Code128Reader.cpp",
    "zxing/oned/Code128Reader.h",
    "zxing/oned/Code39Reader.cpp",
    "zxing/oned/Code39Reader.h",
    "zxing/oned/Code93Reader.cpp",
    "zxing/oned/Code93Reader.h",
    "zxing/oned/EAN13Reader.cpp",
    "zxing/oned/EAN13Reader.h",
    "zxing/oned/EAN8Reader.cpp",
    "zxing/oned/EAN8Reader.h",
    "zxing/oned/ITFReader.cpp",
    "zxing/oned/ITFReader.h",
    "zxing/oned/MultiFormatOneDReader.cpp",
    "zxing/oned/MultiFormatOneDReader.h",
    "zxing/oned/MultiFormatUPCEANReader.cpp",
    "zxing/oned/MultiFormatUPCEANReader.h",
    "zxing/oned/OneDReader.cpp",
    "zxing/oned/OneDReader.h",
    "zxing/oned/OneDResultPoint.cpp",
    "zxing/oned/OneDResultPoint.h",
    "zxing/oned/UPCAReader.cpp",
    "zxing/oned/UPCAReader.h",
    "zxing/oned/UPCEANReader.cpp",
    "zxing/oned/UPCEANReader.h",
    "zxing/oned/UPCEReader.cpp",
    "zxing/oned/UPCEReader.h",
    "zxing/pdf417/decoder/BitMatrixParser.cpp",
    "zxing/pdf417/decoder/BitMatrixParser.h",
    "zxing/pdf417/decoder/DecodedBitStreamParser.cpp",
    "zxing/pdf417/decoder/DecodedBitStreamParser.h",
    "zxing/pdf417/decoder/Decoder.cpp",
    "zxing/pdf417/decoder/Decoder.h",
    "zxing/pdf417/decoder/ec/ErrorCorrection.cpp",
    "zxing/pdf417/decoder/ec/ErrorCorrection.h",
    "zxing/pdf417/decoder/ec/ModulusGF.cpp",
    "zxing/pdf417/decoder/ec/ModulusGF.h",
    "zxing/pdf417/decoder/ec/ModulusPoly.cpp",
    "zxing/pdf417/decoder/ec/ModulusPoly.h",
    "zxing/pdf417/detector/Detector.cpp",
    "zxing/pdf417/detector/Detector.h",
    "zxing/pdf417/detector/LinesSampler.cpp",
    "zxing/pdf417/detector/LinesSampler.h",
    "zxing/pdf417/PDF417Reader.cpp",
    "zxing/pdf417/PDF417Reader.h",
    "zxing/qrcode/decoder/BitMatrixParser.cpp",
    "zxing/qrcode/decoder/BitMatrixParser.h",
    "zxing/qrcode/decoder/DataBlock.cpp",
    "zxing/qrcode/decoder/DataBlock.h",
    "zxing/qrcode/decoder/DataMask.cpp",
    "zxing/qrcode/decoder/DataMask.h",
    "zxing/qrcode/decoder/DecodedBitStreamParser.cpp",
    "zxing/qrcode/decoder/DecodedBitStreamParser.h",
    "zxing/qrcode/decoder/Decoder.cpp",
    "zxing/qrcode/decoder/Decoder.h",
    "zxing/qrcode/decoder/Mode.cpp",
    "zxing/qrcode/decoder/Mode.h",
    "zxing/qrcode/detector/AlignmentPattern.cpp",
    "zxing/qrcode/detector/AlignmentPattern.h",
    "zxing/qrcode/detector/AlignmentPatternFinder.cpp",
    "zxing/qrcode/detector/AlignmentPatternFinder.h",
    "zxing/qrcode/detector/Detector.cpp",
    "zxing/qrcode/detector/Detector.h",
    "zxing/qrcode/detector/FinderPattern.cpp",
    "zxing/qrcode/detector/FinderPattern.h",
    "zxing/qrcode/detector/FinderPatternFinder.cpp",
    "zxing/qrcode/detector/FinderPatternFinder.h",
    "zxing/qrcode/detector/FinderPatternInfo.cpp",
    "zxing/qrcode/detector/FinderPatternInfo.h",
    "zxing/qrcode/ErrorCorrectionLevel.cpp",
    "zxing/qrcode/ErrorCorrectionLevel.h",
    "zxing/qrcode/FormatInformation.cpp",
    "zxing/qrcode/FormatInformation.h",
    "zxing/qrcode/QRCodeReader.cpp",
    "zxing/qrcode/QRCodeReader.h",
    "zxing/qrcode/Version.cpp",
    "zxing/qrcode/Version.h",
    "zxing/Reader.cpp",
    "zxing/Reader.h",
    "zxing/ReaderException.h",
    "zxing/Result.cpp",
    "zxing/Result.h",
    "zxing/ResultIO.cpp",
    "zxing/ResultPoint.cpp",
    "zxing/ResultPoint.h",
    "zxing/ResultPointCallback.cpp",
    "zxing/ResultPointCallback.h",
    "zxing/ZXing.h",
];

fn main() {
    let mut builder = cc::Build::new();
    let mut bindgen_builder = bindgen::builder()
        .header("src/wrapper.hpp")
        .clang_arg(format!("-I{}", ZXING_SRC))
        .clang_arg("-std=c++14")
        .enable_cxx_namespaces()
        .opaque_type("std.*")
        .whitelist_type("zxing::.*");

    builder.cpp(true).include(ZXING_SRC);

    for file in FILE_LIST.iter() {
        builder.file(PathBuf::from(ZXING_SRC).join(file));
    }

    if env::var("TARGET").unwrap() == "armv7-unknown-linux-gnueabihf" {
        let sys_include = [
            "/usr/arm-linux-gnueabihf/include",
            "/usr/arm-linux-gnueabihf/include/c++/8",
            "/usr/arm-linux-gnueabihf/include/c++/8/arm-linux-gnueabihf",
        ];

        for include in sys_include.iter() {
            builder.include(include);
            bindgen_builder = bindgen_builder.clang_arg(format!("-I{}", include));
        }
    }

    let compile = thread::spawn(move || builder.compile("zxing"));

    bindgen_builder
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(PathBuf::from(env::var("OUT_DIR").unwrap()).join("bindings.rs"))
        .expect("Couldn't write bindings!");

    compile.join().unwrap();
}
